ALTER TABLE characters
  ADD COLUMN str_score INTEGER NOT NULL DEFAULT 10,
  ADD COLUMN dex_score INTEGER NOT NULL DEFAULT 10,
  ADD COLUMN con_score INTEGER NOT NULL DEFAULT 10,
  ADD COLUMN int_score INTEGER NOT NULL DEFAULT 10,
  ADD COLUMN wis_score INTEGER NOT NULL DEFAULT 10,
  ADD COLUMN cha_score INTEGER NOT NULL DEFAULT 10;
