-- CRB Technomancer-only spells (not on Mystic list).
-- UUIDs use prefix e3 (Technomancer spells).
-- Stats sourced from Starfinder CRB / Archives of Nethys (aonprd.com).

INSERT INTO spells (id, name, school, casting_time, range, area, targets, duration, saving_throw, spell_resist, description, damage, damage_note) VALUES

-- Level 0 (Technomancer only)
('e3000000-0000-0000-0000-000000000001', 'Mending',             'transmutation', '10 minutes', 'touch',  NULL, 'one object of up to 1 lb.', 'instantaneous', 'Will negates (harmless, object)', 'yes (harmless, object)', 'Mending repairs damage to an object, restoring 1d4 Hit Points to the target object. Broken objects cannot be repaired with mending (use make whole instead). Magic items can be repaired by this spell, but the spell cannot restore their dweomer.', NULL, NULL),
('e3000000-0000-0000-0000-000000000002', 'Transfer Charge',     'transmutation', '1 standard action', 'touch', NULL, 'two objects of the same type (either two batteries or two items with charges)', 'instantaneous', 'none', 'no', 'You transfer any number of charges from one object to another object of the same type, as long as the objects can hold the same type of charge (usually battery charges). You can''t give an object more charges than its maximum capacity, and any excess charges are lost.', NULL, NULL),

-- Level 1 (Technomancer only)
('e3000000-0000-0000-0000-000000000101', 'Detect Tech',         'divination',  '1 standard action', '60 ft.', '60-ft. cone-shaped emanation', NULL, 'concentration, up to 1 min./level (D)', 'none', 'no', 'You detect the presence and location of technological items and creatures. 1st round: Presence or absence of tech. 2nd round: Number of tech items and the most complex. 3rd round: The location and nature of each tech item.', NULL, NULL),
('e3000000-0000-0000-0000-000000000102', 'Jolting Surge',       'evocation',   '1 standard action', 'touch',  NULL, 'one creature or object', 'instantaneous', 'none', 'yes', 'You touch a target and release a massive surge of electricity. You must succeed at a melee touch attack. If the target is a technological construct or is wearing or holding a technological item, it takes a –2 penalty to the saving throw.', '4d6', 'Electricity damage.'),
('e3000000-0000-0000-0000-000000000103', 'Magic Missile',       'evocation',   '1 standard action', 'medium (100 ft. + 10 ft./level)', NULL, 'up to three creatures, no two of which can be more than 15 ft. apart', 'instantaneous', 'none', 'yes', 'You fire two missiles of magical energy that strike your target unerringly, even if it is in melee combat or has cover or concealment. Each missile deals 1d4+1 force damage. The missiles can strike the same or different targets, but all targets must be designated before you roll damage. You fire one additional missile per four caster levels beyond 1st (two at 5th level, three at 9th).', '1d4+1 force per missile', 'Missiles: 1 (CL 1), 2 (CL 5), 3 (CL 9).'),
('e3000000-0000-0000-0000-000000000104', 'Overheat',            'evocation',   '1 standard action', '15 ft.', '15-ft. cone', NULL, 'instantaneous', 'Reflex half', 'yes', 'You vent heat in a cone. Creatures in the area take fire damage.', '2d8', 'Fire damage.'),
('e3000000-0000-0000-0000-000000000105', 'Grease',              'conjuration', '1 standard action', 'close (25 ft. + 5 ft./2 levels)', 'one 10-ft. square', NULL, '1 min./level (D)', 'see text', 'no', 'A grease spell covers a solid surface with a layer of slippery grease. Any creature in the area when the spell is cast must succeed at a Reflex save or fall. A creature can walk within or through the area of grease at half normal speed with a successful DC 10 Acrobatics check. Failure means it can''t move that round (and must then make a Reflex save or fall), while failure by 5 or more means it falls.', NULL, NULL),
('e3000000-0000-0000-0000-000000000106', 'Unseen Servant',      'conjuration', '1 standard action', 'close (25 ft. + 5 ft./2 levels)', NULL, NULL, '1 hour/level', 'none', 'no', 'You conjure an invisible, mindless, shapeless force that performs simple tasks. It obeys your commands and follows your directions. It can open only normal doors, drawers, lids, and the like. It has an effective Strength score of 2 (so it can lift 20 pounds or drag 100 pounds). It can trigger traps and such, but it can exert only 20 pounds of force. The servant cannot attack in any way; it is never allowed an attack roll. It cannot be killed, but it dissipates if it takes 6 or more points of damage from area attacks (it gets no saves against attacks).', NULL, NULL),

-- Level 2 (Technomancer only)
('e3000000-0000-0000-0000-000000000201', 'Arcane Sight',        'divination',  '1 standard action', 'personal', NULL, 'you', '1 min./level (D)', 'none', 'no', 'This spell makes your eyes glow blue and allows you to see magical auras within 120 feet of you. The effect is similar to that of a detect magic spell, but arcane sight does not require concentration and discerns aura location and power more quickly. You know the location and power of all magical auras within your sight. An aura''s power depends on a spell''s functioning level or an item''s caster level.', NULL, NULL),
('e3000000-0000-0000-0000-000000000202', 'Caustic Conversion',  'conjuration', '1 standard action', 'medium (100 ft. + 10 ft./level)', NULL, 'one creature', 'instantaneous', 'none', 'yes', 'You fire a glob of semi-solid acid that converts into a spray on impact, dealing acid damage and the corrode critical hit effect. You must succeed at a ranged touch attack.', '3d8', 'Acid damage; on a critical hit, the target also takes the corrode 2d6 effect.'),
('e3000000-0000-0000-0000-000000000203', 'Elemental Convergence', 'evocation', '1 standard action', 'medium (100 ft. + 10 ft./level)', NULL, 'one creature', 'instantaneous', 'Reflex half', 'yes', 'You call on a convergence of elemental energy to assail the target with multiple energy types. Choose two of the following energy types: acid, cold, electricity, fire, or sonic. The target takes damage of each chosen type.', '2d6 + 2d6', 'Each energy type deals 2d6 damage (total 4d6); Reflex half applies to the total.'),
('e3000000-0000-0000-0000-000000000204', 'Inject Nanobots',     'necromancy',  '1 standard action', 'touch', NULL, 'one creature', 'instantaneous and 1 round/level; see text', 'Fort negates', 'yes', 'You inject a swarm of nanobots into the target with a melee touch attack. On a failed save, the nanobots cause the target to be confused for 1 round per level as they disrupt neural pathways. They also deal 2d8 damage initially. Constructs and technological creatures are especially vulnerable (–2 to save).', '2d8', NULL),
('e3000000-0000-0000-0000-000000000205', 'Microbot Assault',    'conjuration', '1 standard action', 'close (25 ft. + 5 ft./2 levels)', NULL, NULL, '1 round/level', 'Fort negates; see text', 'no', 'You create a cloud of tiny microbots that harry and harass a single creature within range. The microbots follow the target and distract it. The target is off-target while this spell persists.', NULL, NULL),
('e3000000-0000-0000-0000-000000000206', 'Recharge',            'transmutation','1 standard action', 'touch', NULL, 'one technological object', 'instantaneous', 'Will negates (harmless, object)', 'no', 'You restore charges to one technological item. You can restore up to 5 charges + 1 per caster level (maximum +10) to the target item, but the item cannot exceed its full charge capacity.', NULL, NULL),

-- Level 3 (Technomancer only)
('e3000000-0000-0000-0000-000000000301', 'Arcing Surge',        'evocation',   '1 standard action', '120 ft.', '120-ft. line', NULL, 'instantaneous', 'Reflex half', 'yes', 'You release a powerful surge of electricity in a line. Creatures in the area take electricity damage.', '10d6', 'Electricity damage.'),
('e3000000-0000-0000-0000-000000000302', 'Explosive Blast',     'evocation',   '1 standard action', 'medium (100 ft. + 10 ft./level)', '20-ft.-radius spread', NULL, 'instantaneous', 'Reflex half', 'yes', 'A massive explosion of fire engulfs the target area.', '9d6', 'Fire damage.'),
('e3000000-0000-0000-0000-000000000303', 'Irradiate',           'evocation',   '1 standard action', 'medium (100 ft. + 10 ft./level)', '10-ft.-radius spread', NULL, 'instantaneous', 'Fort half', 'yes', 'A burst of radiation fills the area. Creatures in the area take fire damage and are exposed to medium radiation (Fortitude DC = spell save DC).', '4d6', 'Fire damage plus medium radiation exposure on failed Fortitude save.'),
('e3000000-0000-0000-0000-000000000304', 'Handy Junkbot',       'transmutation','1 round',           'close (25 ft. + 5 ft./2 levels)', NULL, NULL, '1 round/level (D)', 'none', 'no', 'You animate a pile of junk into a Small construct (the handy junkbot) that can use the aid another action or perform skills on your behalf. It has BAB equal to your caster level and can Aid Another for Engineering, Computers, or Sleight of Hand. It has HP equal to twice your caster level and is destroyed if reduced to 0 HP.', NULL, NULL),
('e3000000-0000-0000-0000-000000000305', 'Slow',                'transmutation','1 standard action', 'close (25 ft. + 5 ft./2 levels)', '30-ft.-radius spread', NULL, '1 round/level', 'Will negates', 'yes', 'An affected creature moves and attacks at a drastically slowed rate. Affected creatures can take only one move action or standard action each turn (not both, and no full action), and they can''t make iterative attacks. Slowed creatures receive –1 penalties to AC, melee attack rolls, melee damage rolls, and Reflex saves. A slowed creature moves at half its normal speed (round down to the next 5-foot increment).', NULL, NULL),

-- Level 4 (Technomancer only)
('e3000000-0000-0000-0000-000000000401', 'Control Atmosphere',  'transmutation','1 standard action', 'medium (100 ft. + 10 ft./level)', '50-ft.-radius emanation', NULL, 'concentration, up to 1 min./level (D)', 'Fort negates; see text', 'no', 'You take control of the atmosphere in the area, altering it however you choose. Options include: changing air pressure, removing or adding air, creating strong winds, controlling temperature (hot or cold), or adding or removing environmental hazards such as extreme temperatures. Creatures in the area take appropriate environmental damage each round.', NULL, NULL),
('e3000000-0000-0000-0000-000000000402', 'Overload Systems',    'evocation',   '1 standard action', 'close (25 ft. + 5 ft./2 levels)', NULL, 'one creature or construct', 'instantaneous and 1 round/level', 'Fort negates', 'yes', 'You overload the target''s systems (biological or technological), dealing 10d6 electricity damage. On a failed save, the target is also staggered for 1 round per level.', '10d6', 'Electricity damage.'),
('e3000000-0000-0000-0000-000000000403', 'Resistant Armor',     'abjuration',  '1 standard action', 'touch', NULL, 'armor touched', '1 min./level', 'Will negates (harmless, object)', 'yes (harmless, object)', 'You infuse the target armor with magical energy that grants DR 5/– against a single energy type of your choice (acid, cold, electricity, fire, or sonic) to its wearer.', NULL, NULL),
('e3000000-0000-0000-0000-000000000404', 'Animate Dead',        'necromancy',  '1 standard action', 'touch', NULL, 'one or more corpses', 'instantaneous', 'none', 'no', 'This spell turns the bones or bodies of dead creatures into undead skeletons or zombies that follow your spoken commands. You can animate a number of HD of undead equal to twice your caster level. These undead obey your commands until destroyed, the spell is dispelled, or (if undead) they are turned. Undead created by this spell are not automatically friendly toward you; they simply follow your commands. The maximum number of HD of undead you can control is 4 times your caster level.', NULL, NULL),

-- Level 5 (Technomancer only)
('e3000000-0000-0000-0000-000000000501', 'Communion with Data', 'divination',  '10 minutes', 'personal', NULL, 'you', 'instantaneous', 'none', 'no', 'You commune with a massive repository of data, asking it one yes-or-no question per two caster levels (maximum 10 questions). Each question has a 75% chance of being answered correctly; the remaining 25% results in an incorrect answer. The data repository is vast but not omniscient; it knows only what is commonly recorded or has been fed into connected networks.', NULL, NULL),
('e3000000-0000-0000-0000-000000000502', 'Fabricate',           'transmutation','1 minute/10 cu. ft.', 'close (25 ft. + 5 ft./2 levels)', NULL, 'up to 10 cu. ft./level of raw material', 'instantaneous', 'none', 'no', 'You convert raw materials into finished items. For example, you can fabricate a stone door from a boulder, a bookcase from a forest, a suit of armor from iron ore, and so on. Creature-created fabrications are typically of average quality. Fabricate cannot create magic items.', NULL, NULL),
('e3000000-0000-0000-0000-000000000503', 'Fuse Armor',          'transmutation','1 standard action', 'touch', NULL, 'armor worn by creature touched', '1 round/level', 'Fort negates', 'yes', 'You magically fuse the target''s armor to its body, preventing the target from removing the armor and imposing a –4 penalty to Dexterity-based skill checks. The target also cannot take actions that require full use of its arms unless wearing armor that permits them. At the end of each round, the target can attempt a new Fortitude save to end the effect.', NULL, NULL),

-- Level 6 (Technomancer only)
('e3000000-0000-0000-0000-000000000601', 'Disintegrate',        'transmutation','1 standard action', 'medium (100 ft. + 10 ft./level)', NULL, 'one creature or object', 'instantaneous', 'Fort partial (object Fort negates)', 'yes', 'A thin, green ray springs from your pointing finger. You must make a successful ranged touch attack to hit. Any creature struck by the ray takes 15d6 damage. If the damage caused to an unattended nonmagical object exceeds the object''s HP, the object is disintegrated. If this damage kills a creature or if it is used against an object, the target is reduced to a trace of fine dust. Only a wish or miracle can restore a disintegrated creature.', '15d6', NULL),
('e3000000-0000-0000-0000-000000000602', 'Ethereal Jaunt',      'transmutation','1 standard action', 'personal', NULL, 'you', '1 round/level (D)', 'none', 'no', 'You become ethereal along with your equipment. For the duration, you are in the Ethereal Plane, which overlaps the Material Plane. You become invisible and weightless. You can move in any direction, even up or down. Solid objects on the Material Plane do not block your movement (though you cannot see what''s there). You can observe but not affect the Material Plane and can''t attack or be attacked.', NULL, NULL),
('e3000000-0000-0000-0000-000000000603', 'Rewire Flesh',        'transmutation','1 standard action', 'close (25 ft. + 5 ft./2 levels)', NULL, 'one humanoid', 'instantaneous (permanent)', 'Fort negates', 'yes', 'You twist the target''s biological processes, transforming its flesh into electronic components. The target takes 13d6 damage. If the target fails its saving throw, it is also permanently transformed: its type changes to construct. This is permanent until removed by remove affliction or a wish.', '13d6', NULL);
