-- CRB Mystic-only spells (not on Technomancer list).
-- UUIDs use prefix e2 (Mystic spells).
-- Stats sourced from Starfinder CRB / Archives of Nethys (aonprd.com).

INSERT INTO spells (id, name, school, casting_time, range, area, targets, duration, saving_throw, spell_resist, description, damage, damage_note) VALUES

-- Level 0 (Mystic only)
('e2000000-0000-0000-0000-000000000001', 'Detect Affliction',  'divination',  '1 standard action', 'close (25 ft. + 5 ft./2 levels)', NULL, 'one creature or object', 'instantaneous', 'none', 'no', 'You determine whether a creature or object is afflicted with a disease or a curse, and with a successful DC 20 Mysticism check you can determine the exact nature of the affliction.', NULL, NULL),
('e2000000-0000-0000-0000-000000000002', 'Psychokinetic Hand', 'transmutation','1 standard action', 'close (25 ft. + 5 ft./2 levels)', NULL, 'one unattended object of up to 5 lbs.', 'concentration', 'none', 'no', 'You create a sustained invisible telekinetic force that can move or manipulate an object. Move an object 15 feet per round. A windwall can deflect this. You can use this to make trip attacks against foes (CMB = your caster level + your key ability modifier).', NULL, NULL),
('e2000000-0000-0000-0000-000000000003', 'Stabilize',          'necromancy',  '1 standard action', 'close (25 ft. + 5 ft./2 levels)', NULL, 'one dying creature', 'instantaneous', 'Will negates (harmless)', 'yes (harmless)', 'You cause a living creature that is dying to stabilize immediately. This causes the creature to stabilize and stop dying, though it does not heal the creature. The creature must still succeed at recovery checks, but they now start from a stabilized state.', NULL, NULL),

-- Level 1 (Mystic only)
('e2000000-0000-0000-0000-000000000101', 'Charm Person',       'enchantment', '1 standard action', 'close (25 ft. + 5 ft./2 levels)', NULL, 'one humanoid creature', '1 hour/level', 'Will negates', 'yes', 'This charm makes a humanoid creature regard you as its trusted friend and ally (treat the target''s attitude as friendly). The target creature won''t attack you, and it will assist you if asked, though it won''t place itself in obvious danger.', NULL, NULL),
('e2000000-0000-0000-0000-000000000102', 'Command',            'enchantment', '1 standard action', 'close (25 ft. + 5 ft./2 levels)', NULL, 'one living creature', '1 round', 'Will negates', 'yes', 'You give the subject a single command, which it obeys to the best of its ability at its earliest opportunity. You may select from the following options: approach, drop, fall, flee, or halt. Approach: On its turn, the subject moves toward you as quickly and directly as possible for 1 round. The creature may do nothing but move during its turn. Drop: The subject drops whatever it is holding. It can''t pick up any dropped item until after the spell ends. Fall: The subject falls to the ground and remains prone for 1 round. It may act normally while prone but takes any appropriate penalties. Flee: On its turn, the subject moves away from you as quickly as possible for 1 round. Halt: The subject doesn''t move or take any actions for 1 round.', NULL, NULL),
('e2000000-0000-0000-0000-000000000103', 'Detect Thoughts',    'divination',  '1 standard action', '60 ft.',                          '60-ft. cone-shaped emanation', NULL, 'concentration, up to 1 min./level (D)', 'Will negates; see text', 'no', 'You detect surface thoughts. The amount of information revealed depends on how long you study a particular area or subject. 1st round: The presence or absence of thoughts from conscious creatures within the area. 2nd round: The number of thinking minds and the Intelligence score of each. 3rd round: Surface thoughts of any mind in the area. A target of this spell can attempt a Will saving throw to prevent you from reading their thoughts.', NULL, NULL),
('e2000000-0000-0000-0000-000000000104', 'Lesser Confusion',   'enchantment', '1 standard action', 'close (25 ft. + 5 ft./2 levels)', NULL, 'one living creature',  '1 round',       'Will negates', 'yes', 'This spell causes a single creature to become confused for 1 round. See the confusion spell for possible effects.', NULL, NULL),
('e2000000-0000-0000-0000-000000000105', 'Mystic Cure',        'conjuration', '1 standard action', 'touch',                           NULL, 'one living creature',  'instantaneous', 'Will negates (harmless)', 'yes (harmless)', 'With a touch, you restore 1d8 hit points + your Wisdom modifier to a living creature. This spell has no effect on constructs, undead, or other unliving creatures.', '1d8 + Wis mod', NULL),
('e2000000-0000-0000-0000-000000000106', 'Share Language',     'divination',  '1 standard action', 'touch',                           NULL, 'one creature',         '24 hours',      'Will negates (harmless)', 'no', 'You grant the target creature the ability to read, write, speak, and understand one language you know. This does not confer any other knowledge or ability.', NULL, NULL),
('e2000000-0000-0000-0000-000000000107', 'Mind Thrust I',      'divination',  '1 standard action', 'close (25 ft. + 5 ft./2 levels)', NULL, 'one creature',         'instantaneous', 'Will half', 'yes', 'You unleash a blast of mental energy that assaults the target''s mind. This spell can target any creature with an Intelligence score.', '2d10', NULL),

-- Level 2 (Mystic only)
('e2000000-0000-0000-0000-000000000201', 'Brain Jolt',         'divination',  '1 standard action', 'close (25 ft. + 5 ft./2 levels)', NULL, 'one creature',         'instantaneous', 'Will partial; see text', 'yes', 'You blast the target''s mind with a surge of mental energy, dealing damage and potentially dazing it. On a failed save, the target is also dazed for 1 round.', '4d8', NULL),
('e2000000-0000-0000-0000-000000000202', 'Calm Emotions',      'enchantment', '1 standard action', 'medium (100 ft. + 10 ft./level)', '20-ft.-radius spread', NULL, 'concentration, up to 1 round/level (D)', 'Will negates', 'yes', 'This spell calms agitated creatures. You have no control over the affected creatures, but calm emotions can stop raging creatures from fighting or joyous ones from reveling. Creatures in the area must succeed at a Will save or be affected. Affected creatures cannot take violent actions (although they can defend themselves) or do anything destructive. Any aggressive action against or damage dealt to a calmed creature immediately breaks the spell.', NULL, NULL),
('e2000000-0000-0000-0000-000000000203', 'Hold Person',        'enchantment', '1 standard action', 'medium (100 ft. + 10 ft./level)', NULL, 'one humanoid creature', '1 round/level (D)', 'Will negates', 'yes', 'The subject becomes paralyzed and freezes in place. It is aware and breathes normally but cannot take any actions, even speech. A winged creature who is paralyzed cannot flap its wings and falls. A swimmer can''t swim and may drown.', NULL, NULL),
('e2000000-0000-0000-0000-000000000204', 'Mystic Cure II',     'conjuration', '1 standard action', 'touch',                           NULL, 'one living creature',  'instantaneous', 'Will negates (harmless)', 'yes (harmless)', 'This spell functions as mystic cure, except it heals more damage.', '3d8 + Wis mod', NULL),
('e2000000-0000-0000-0000-000000000205', 'Restoration (Lesser)', 'conjuration', '1 minute',        'touch',                           NULL, 'one living creature',  'instantaneous', 'Will negates (harmless)', 'yes (harmless)', 'Lesser restoration dispels any magical effects reducing one of the subject''s ability scores or cures 1d4 points of temporary ability damage to one of the subject''s ability scores. It also eliminates any fatigue suffered by the character, and improves an exhausted condition to fatigued. It does not restore permanent ability drain.', NULL, NULL),
('e2000000-0000-0000-0000-000000000206', 'Zone of Truth',      'enchantment', '1 standard action', 'close (25 ft. + 5 ft./2 levels)', '20-ft.-radius emanation', NULL, '1 min./level', 'Will negates', 'yes', 'Creatures within the emanation area (or those who enter it) can''t speak deliberate lies. Affected creatures are aware of this enchantment. Therefore, they may refuse to answer questions, or they may be evasive, as long as they remain within the boundaries of the truth. You can tell when a creature within range is affected (or not). You cannot use the zone to tell whether a specific statement is true.', NULL, NULL),
('e2000000-0000-0000-0000-000000000207', 'Mind Thrust II',     'divination',  '1 standard action', 'close (25 ft. + 5 ft./2 levels)', NULL, 'one creature',         'instantaneous', 'Will half', 'yes', 'This spell functions as mind thrust I, but deals more damage.', '4d10', NULL),

-- Level 3 (Mystic only)
('e2000000-0000-0000-0000-000000000301', 'Bestow Curse',       'necromancy',  '1 standard action', 'touch',                           NULL, 'one creature',         'permanent', 'Will negates', 'yes', 'You place a terrible curse on the subject. Choose one of the following. –6 decrease to one ability score (minimum 1). –4 penalty on attack rolls, saving throws, ability checks, and skill checks. Each turn, the target has a 50% chance to act normally; otherwise, it takes no action. You may also invent your own curse, but it should be no more powerful than those described above. The curse bestowed by this spell cannot be dispelled, but it can be removed with a break enchantment, limited wish, miracle, remove curse, or wish spell.', NULL, NULL),
('e2000000-0000-0000-0000-000000000302', 'Charm Monster',      'enchantment', '1 standard action', 'close (25 ft. + 5 ft./2 levels)', NULL, 'one living creature',  '1 day/level',   'Will negates', 'yes', 'This spell functions like charm person, except that the effect is not limited to humanoid creatures.', NULL, NULL),
('e2000000-0000-0000-0000-000000000303', 'Deep Slumber',       'enchantment', '1 round',           'close (25 ft. + 5 ft./2 levels)', NULL, 'one or more living creatures within a 10-ft.-radius burst', '1 min./level', 'Will negates', 'yes', 'A cone of soporific energy causes creatures in the area to fall into a magical sleep. Roll 10d8 to determine the total Hit Points of creatures affected. Creatures with the fewest Hit Points are affected first. Among creatures with equal Hit Points, those who are closest to the spell''s point of origin are affected first. Sleeping creatures are helpless. Slapping or wounding awakens an affected creature, but normal noise does not. Awakening a creature is a standard action (an application of the aid another action).', NULL, NULL),
('e2000000-0000-0000-0000-000000000304', 'Mystic Cure III',    'conjuration', '1 standard action', 'touch',                           NULL, 'one living creature',  'instantaneous', 'Will negates (harmless)', 'yes (harmless)', 'This spell functions as mystic cure, except it heals more damage.', '5d8 + Wis mod', NULL),
('e2000000-0000-0000-0000-000000000305', 'Remove Affliction',  'conjuration', '1 minute',          'touch',                           NULL, 'one creature',         'instantaneous', 'Fort negates (harmless)', 'yes (harmless)', 'You remove all curses, diseases, and poisons from the target creature. You can also use this spell to remove a condition caused by one of these afflictions.', NULL, NULL),
('e2000000-0000-0000-0000-000000000306', 'Mind Thrust III',    'divination',  '1 standard action', 'close (25 ft. + 5 ft./2 levels)', NULL, 'one creature',         'instantaneous', 'Will half', 'yes', 'This spell functions as mind thrust I, but deals more damage and the target is also fatigued on a failed save.', '7d10', NULL),

-- Level 4 (Mystic only)
('e2000000-0000-0000-0000-000000000401', 'Atonement',          'abjuration',  '1 hour',            'touch',                           NULL, 'living creature touched', 'instantaneous', 'none', 'yes', 'This spell removes the burden of misdeeds from the subject. The creature seeking atonement must be truly repentant and desirous of setting right its misdeeds. Atoning for wilful acts of evil requires material components, but unintentional acts do not.', NULL, NULL),
('e2000000-0000-0000-0000-000000000402', 'Break Enchantment',  'abjuration',  '1 minute',          'close (25 ft. + 5 ft./2 levels)', NULL, 'up to one creature/level, all within 30 ft. of each other', 'instantaneous', 'see text', 'no', 'This spell frees victims from enchantments, transmutations, and curses. Break enchantment can reverse even an instantaneous effect. For each such effect, you make a caster level check (1d20 + caster level, maximum +15) against a DC of 11 + the effect''s caster level. On a success, the effect is suppressed or ended. If the effect comes from a permanent magic item, the item is not destroyed, but the item''s magical power is suppressed for 1d4 rounds.', NULL, NULL),
('e2000000-0000-0000-0000-000000000403', 'Mind Probe',         'divination',  '1 minute',          'close (25 ft. + 5 ft./2 levels)', NULL, 'one creature',         '1 round/level', 'Will negates', 'no', 'You probe the target''s mind and can attempt to learn information. Once per round, as a standard action, you may ask the target one question and it must attempt a Will saving throw. On a failure, it truthfully answers the question to the best of its ability.', NULL, NULL),
('e2000000-0000-0000-0000-000000000404', 'Mystic Cure IV',     'conjuration', '1 standard action', 'touch',                           NULL, 'one living creature',  'instantaneous', 'Will negates (harmless)', 'yes (harmless)', 'This spell functions as mystic cure, except it heals more damage.', '8d8 + Wis mod', NULL),
('e2000000-0000-0000-0000-000000000405', 'Reincarnate',        'transmutation','10 minutes',        'touch',                           NULL, 'dead creature touched', 'instantaneous', 'none (see text)', 'yes (harmless)', 'With this spell, you bring back a dead creature in another body, provided that its death occurred no more than 1 week before the casting of the spell. The reincarnated creature recalls the majority of its former life and knowledge but may have different racial abilities, ability score adjustments, and appearance. The creature appears as a new adult of a random humanoid race.', NULL, NULL),
('e2000000-0000-0000-0000-000000000406', 'Mind Thrust IV',     'divination',  '1 standard action', 'close (25 ft. + 5 ft./2 levels)', NULL, 'one creature',         'instantaneous', 'Will half', 'yes', 'This spell functions as mind thrust I, but deals more damage and the target is also exhausted on a failed save.', '8d10', NULL),

-- Level 5 (Mystic only)
('e2000000-0000-0000-0000-000000000501', 'Dominate Person',    'enchantment', '1 round',           'close (25 ft. + 5 ft./2 levels)', NULL, 'one humanoid creature', 'instantaneous', 'Will negates', 'yes', 'You can control the actions of any humanoid creature through a telepathic link that you establish with the subject''s mind. If you and the subject have a common language, you can generally force the subject to perform as you desire, within the limits of its abilities. If no common language exists, you can communicate only basic commands, such as come here, go there, fight, stand still. You know what the subject is experiencing, but you do not receive direct sensory input from it, nor can it communicate with you telepathically.', NULL, NULL),
('e2000000-0000-0000-0000-000000000502', 'Feeblemind',         'enchantment', '1 standard action', 'medium (100 ft. + 10 ft./level)', NULL, 'one creature',         'instantaneous', 'Will negates', 'yes', 'If the target fails its saving throw, its Intelligence and Charisma scores each drop to 1. The affected creature is unable to use Intelligence- or Charisma-based skills, cast spells, understand language, or communicate coherently. Still, it knows who its friends are and can follow them and even protect them. The subject remains in this state until a heal or restoration spell is used to cancel the effect of the feeblemind.', NULL, NULL),
('e2000000-0000-0000-0000-000000000503', 'Mystic Cure V',      'conjuration', '1 standard action', 'touch',                           NULL, 'one living creature',  'instantaneous', 'Will negates (harmless)', 'yes (harmless)', 'This spell functions as mystic cure, except it heals more damage.', '13d8 + Wis mod', NULL),
('e2000000-0000-0000-0000-000000000504', 'Modify Memory',      'enchantment', '1 round',           'close (25 ft. + 5 ft./2 levels)', NULL, 'one creature',         'permanent',     'Will negates', 'yes', 'You reach into the subject''s mind and modify as many as 5 minutes of its memories in one of the following ways: eliminate an event, allow the subject to recall with perfect clarity an event it actually experienced, change the details of an event, or implant a memory of an event it never experienced.', NULL, NULL),
('e2000000-0000-0000-0000-000000000505', 'Mind Thrust V',      'divination',  '1 standard action', 'close (25 ft. + 5 ft./2 levels)', NULL, 'one creature',         'instantaneous', 'Will half', 'yes', 'This spell functions as mind thrust I, but deals more damage and the target is stunned for 1 round on a failed save.', '12d10', NULL),

-- Level 6 (Mystic only)
('e2000000-0000-0000-0000-000000000601', 'Dominate Monster',   'enchantment', '1 round',           'close (25 ft. + 5 ft./2 levels)', NULL, 'one creature',         'instantaneous', 'Will negates', 'yes', 'This spell functions like dominate person, except that the effect is not limited to humanoid creatures.', NULL, NULL),
('e2000000-0000-0000-0000-000000000602', 'Heal',               'conjuration', '1 standard action', 'touch',                           NULL, 'one living creature',  'instantaneous', 'Will negates (harmless)', 'yes (harmless)', 'Heal enables you to channel positive energy into a creature to wipe away injury and afflictions. It immediately ends any and all of the following adverse conditions affecting the target: ability damage (restoring the lost points), blinded, confused, dazed, dazzled, deafened, diseased, exhausted, fatigued, feebleminded, insanity, nauseated, poisoned, sickened, and stunned. It also cures 10 Hit Points per caster level (maximum 150 points).', '10 per CL (max 150 HP)', NULL),
('e2000000-0000-0000-0000-000000000603', 'Mass Suggestion',    'enchantment', '1 standard action', 'medium (100 ft. + 10 ft./level)', NULL, 'one creature/level, no two of which can be more than 30 ft. apart', '1 hour/level (D) or until completed', 'Will negates', 'yes', 'This spell functions like suggestion, except that it can affect more creatures. The same suggestion applies to all these creatures.', NULL, NULL),
('e2000000-0000-0000-0000-000000000604', 'Mind Thrust VI',     'divination',  '1 standard action', 'close (25 ft. + 5 ft./2 levels)', NULL, 'one creature',         'instantaneous', 'Will half', 'yes', 'This spell functions as mind thrust I, but deals more damage and on a failed save the target is stunned for 1d4 rounds.', '15d10', NULL),
('e2000000-0000-0000-0000-000000000605', 'Mystic Cure VI',     'conjuration', '1 standard action', 'touch',                           NULL, 'one living creature',  'instantaneous', 'Will negates (harmless)', 'yes (harmless)', 'This spell functions as mystic cure, except it heals more damage.', '19d8 + Wis mod', NULL);
