-- CRB spells that appear on both the Mystic and Technomancer spell lists.
-- UUIDs use prefix e1 (spells). spell_class rows are added in later migrations.
-- Stats sourced from Starfinder CRB / Archives of Nethys (aonprd.com).

INSERT INTO spells (id, name, school, casting_time, range, area, targets, duration, saving_throw, spell_resist, description, damage, damage_note) VALUES

-- Level 0 (shared)
('e1000000-0000-0000-0000-000000000001', 'Daze',              'enchantment', '1 standard action', 'close (25 ft. + 5 ft./2 levels)', NULL, 'one humanoid creature of CR 3 or lower', '1 round',       'Will negates', 'yes', 'This spell clouds the mind of a humanoid creature with 3 or fewer CR so that it takes no actions. Humanoids of CR 4 or higher are not affected. The dazed creature is not stunned (so attackers get no special advantage against it). After a creature has been dazed by this spell, it is immune to it for 1 minute.', NULL, NULL),
('e1000000-0000-0000-0000-000000000002', 'Detect Magic',      'divination',  '1 standard action', '60 ft.',                            '60-ft. cone-shaped emanation', NULL,                        'concentration, up to 1 min./level', 'none', 'no', 'You detect magical auras. The amount of information revealed depends on how long you study a particular area or subject. 1st round: Presence or absence of magical auras. 2nd round: Number of different magical auras and the power of the most potent aura. 3rd round: The strength and location of each aura. If the items or creatures bearing the auras are in line of sight, you can make Knowledge (Arcana) skill checks to determine the school of magic involved in each.', NULL, NULL),
('e1000000-0000-0000-0000-000000000003', 'Energy Ray',        'evocation',   '1 standard action', 'close (25 ft. + 5 ft./2 levels)', NULL, 'one creature or object',              'instantaneous', 'none', 'yes', 'You blast a target with a ray of your chosen energy type (acid, cold, electricity, or fire). You must choose the energy type when you cast this spell. You must succeed at a ranged touch attack to hit your target.', '1d3', 'Damage type matches chosen energy; increases to 2d3 at caster level 3rd, 3d3 at 5th, 4d3 at 7th, 5d3 at 9th, 6d3 at 11th.'),
('e1000000-0000-0000-0000-000000000004', 'Ghost Sound',       'illusion',    '1 standard action', 'close (25 ft. + 5 ft./2 levels)', NULL, NULL,                                  '1 round/level (D)', 'Will disbelief', 'no', 'Ghost sound allows you to create a volume of sound that rises, recedes, approaches, or remains at a fixed place. You choose what type of sound ghost sound creates when casting it and cannot thereafter change the sound''s basic character. The volume of sound created depends on your level.', NULL, NULL),
('e1000000-0000-0000-0000-000000000005', 'Telepathic Message', 'divination', '1 standard action', 'medium (100 ft. + 10 ft./level)', NULL, 'up to one creature/level',            '10 minutes',    'none', 'no', 'You can whisper messages and receive whispered replies with little chance of being overheard. You point your finger at each creature you want to receive the message. When you whisper, the designated creatures hear the whisper and can whisper a reply that only you can hear. A target can''t use telepathic message to communicate with anyone other than you.', NULL, NULL),
('e1000000-0000-0000-0000-000000000006', 'Token Spell',       'universal',   '1 standard action', 'touch',                           NULL, 'object touched',                      '1 day',         'none', 'no', 'You create a small magical effect of little power. You can use token spell to perform any of the following: color, clean, or soil items in a 1-foot cube; chill, warm, or flavor 1 pound of nonliving material; make a small mark or symbol appear on a surface for 1 day; light or snuff out a candle, torch, or small campfire; make a small noise or cause a brief flash of light; create a small handheld item that persists until dismissed; or bring a small item into or out of a pocket extradimensional space.', NULL, NULL),

-- Level 1 (shared)
('e1000000-0000-0000-0000-000000000101', 'Comprehend Languages', 'divination', '1 standard action', 'personal', NULL, 'you', '10 min./level (D)', 'none', 'no', 'You can understand the spoken words of creatures or read otherwise incomprehensible written messages. The ability to read does not necessarily impart insight into the material, merely its literal meaning. Written magical or coded messages are not revealed. Comprehend languages does not enable you to speak or write an unknown language.', NULL, NULL),
('e1000000-0000-0000-0000-000000000102', 'Identify',           'divination', '1 minute',          'touch',    NULL, 'one object',  'instantaneous', 'none', 'no', 'This spell functions as detect magic, except it gives you a +10 insight bonus to Mysticism checks to identify the properties and command words of magic items (including artifacts). You can identify only one item per casting of this spell and must hold the item in your hands to cast the spell.', NULL, NULL),
('e1000000-0000-0000-0000-000000000103', 'Keen Senses',        'transmutation', '1 standard action', 'touch', NULL, 'one creature', '1 min./level (D)', 'Will negates (harmless)', 'yes (harmless)', 'The target gains low-light vision (if it doesn''t already have it) and a +2 insight bonus to Perception checks.', NULL, NULL),
('e1000000-0000-0000-0000-000000000104', 'Life Bubble',        'abjuration', '1 standard action', 'close (25 ft. + 5 ft./2 levels)', NULL, 'one creature/level, no two of which can be more than 30 ft. apart', '1 day/level (D)', 'Will negates (harmless)', 'yes (harmless)', 'You surround the target creatures with a constant, invisible magical field that provides breathable air, protects against harmful gases and supernatural airborne hazards, and maintains pressure at standard atmospheric pressure. The bubble does not affect environmental temperatures, radiation, or vacuum conditions.', NULL, NULL),
('e1000000-0000-0000-0000-000000000105', 'Reflecting Armor',  'abjuration', '1 standard action', 'personal', NULL, 'you', '1 round/level or until discharged', 'none', 'no', 'You surround yourself with shimmering magical energy that reflects magic missiles back at the caster. Until this spell ends or is discharged, you are immune to magic missile and any magic missile targeting you is redirected back at its caster. Once you have redirected one magic missile, the spell is discharged.', NULL, NULL),
('e1000000-0000-0000-0000-000000000106', 'Supercharge Weapon', 'evocation', '1 standard action', 'touch', NULL, 'one weapon', '1 round or until discharged', 'none', 'no', 'You supercharge the target weapon. The next time it damages a target, it deals 4d6 additional damage of whatever energy type the weapon deals. If the weapon is not an energy weapon, the additional damage is electricity. This extra damage is not multiplied on a critical hit.', '4d6', NULL),

-- Level 2 (shared)
('e1000000-0000-0000-0000-000000000201', 'Darkvision',         'transmutation', '1 standard action', 'touch', NULL, 'one creature', '1 hour/level', 'Will negates (harmless)', 'yes (harmless)', 'The target gains darkvision with a range of 60 feet.', NULL, NULL),
('e1000000-0000-0000-0000-000000000202', 'Fog Cloud',          'conjuration',   '1 standard action', 'medium (100 ft. + 10 ft./level)', '20-ft.-radius sphere', NULL, '10 min./level (D)', 'none', 'no', 'A bank of fog billows out from the point you designate. The fog obscures all sight beyond 5 feet, including darkvision. A creature within 5 feet has concealment (attacks have a 20% miss chance). Creatures farther away have total concealment (50% miss chance, and the attacker can''t use sight to locate the target). A moderate wind (11+ mph) disperses the fog in 4 rounds; a strong wind (21+ mph) disperses the fog in 1 round. The spell does not function underwater.', NULL, NULL),
('e1000000-0000-0000-0000-000000000203', 'Invisibility',       'illusion',      '1 standard action', 'personal or touch', NULL, 'you or one creature or one object weighing no more than 100 lbs./level', '1 min./level (D)', 'Will negates (harmless, object)', 'yes (harmless, object)', 'The creature or object touched becomes invisible. If the recipient is a creature carrying gear, that vanishes too. If you cast the spell on someone else, neither you nor your allies can see the subject, unless you can normally see invisible things or employ magic to do so. Items dropped or put down by an invisible creature become visible; items picked up disappear if tucked into the clothing or pouches worn by the creature. Light, however, never becomes invisible, although a source of light can become so. Attacking makes the subject visible. The spell ends if the subject attacks. For the purposes of this spell, an attack includes any spell targeting a foe or whose area or effect includes a foe.', NULL, NULL),
('e1000000-0000-0000-0000-000000000204', 'Knock',              'transmutation', '1 standard action', 'medium (100 ft. + 10 ft./level)', NULL, 'one door, box, chest, or other locked, held, or barred object', 'instantaneous; see text', 'none', 'no', 'Knock opens stuck, barred, or locked doors, as well as those subject to hold portal or arcane lock. When you complete the casting of this spell, make one Mysticism check (1d20 + your caster level) against the DC of the lock or door. On a success, the knock opens up to two means of closure (locks, bars, or latches) on the target door, box, or chest, all mechanisms joining to produce a click. If the door has multiple locks, only one is unlocked per cast. A knock spell does not remove the bar from a barred door, but it does fling the bar aside, leaving the door free to open.', NULL, NULL),
('e1000000-0000-0000-0000-000000000205', 'Mirror Image',       'illusion',      '1 standard action', 'personal', NULL, 'you', '1 min./level (D)', 'none', 'no', 'Several illusory duplicates of you pop into being, making it difficult for enemies to know which target to attack. The figments stay near you and disappear when struck. 1d4 images are created, +1 per 3 caster levels (max 8). Figments mimic your actions, making it difficult for opponents to attack you. Any time you are attacked or are the target of a spell that requires an attack roll, there is a possibility that the attack targets one of your figments instead. If a figment is struck by a melee or ranged attack, it is destroyed. Figments are not affected by area attacks or anything that doesn''t require an attack roll. Each figment has as many HP as 1 point. Spells and effects that don''t deal HP damage are not affected by the images.', NULL, NULL),

-- Level 3 (shared)
('e1000000-0000-0000-0000-000000000301', 'Dispel Magic',       'abjuration', '1 standard action', 'medium (100 ft. + 10 ft./level)', NULL, 'one spellcaster, creature, or object', 'instantaneous', 'none', 'no', 'You can use dispel magic to end one ongoing spell that has been cast on a creature or object, to temporarily suppress the magical abilities of a magic item, or to counter another spellcaster''s spell. A dispelled spell ends as if its duration had expired. A suppressed magic item becomes nonmagical for 1d4 rounds. A dispel magic spell can dispel one spell for every four caster levels you have (maximum five spells at caster level 20th). You choose to use dispel magic as a targeted dispel or area dispel.', NULL, NULL),
('e1000000-0000-0000-0000-000000000302', 'Haste',              'transmutation', '1 standard action', 'close (25 ft. + 5 ft./2 levels)', NULL, 'one creature/level, no two of which can be more than 30 ft. apart', '1 round/level', 'Fort negates (harmless)', 'yes (harmless)', 'The transmuted creatures move and act more quickly than normal. This extra speed has several effects: When taking a full action, a hasted creature may make one extra attack with one natural weapon or manufactured weapon. The attack is made using the creature''s full base attack bonus, plus any modifiers appropriate to the situation. (This effect is not cumulative with similar effects, such as that provided by a weapon with the speed fusion, nor does it actually grant an extra action, so you can''t use it to cast a second spell or otherwise take an extra action in the round.) A hasted creature gains a +1 bonus to attack rolls and a +1 dodge bonus to AC and Reflex saves. Any condition that makes you lose your Dexterity bonus to AC also makes you lose dodge bonuses. All of the hasted creature''s modes of movement (including land movement, burrow, climb, fly, and swim) increase by 30 feet, to a maximum of twice the subject''s normal speed using that form of movement. This increase counts as an enhancement bonus, and it affects the creature''s jumping distance as normal for increased speed. Multiple haste effects don''t stack.', NULL, NULL),
('e1000000-0000-0000-0000-000000000303', 'Tongues',            'divination', '1 standard action', 'touch', NULL, 'one creature', '10 min./level', 'Will negates (harmless)', 'no', 'This spell grants the creature touched the ability to speak and understand the language of any intelligent creature, whether it is a racial tongue or a regional dialect. The subject can speak only one language at a time, although it may be able to understand several languages. Tongues does not enable the subject to speak with creatures that don''t have a language or to understand something that has no language (such as a magic aura). The subject can make itself understood as far as its voice carries. This spell does not predispose any creature addressed toward the subject in any way. Tongues can be made permanent with the make whole spell.', NULL, NULL),

-- Level 4 (shared)
('e1000000-0000-0000-0000-000000000401', 'Dimension Door',     'conjuration', '1 standard action', 'long (400 ft. + 40 ft./level)', NULL, 'you and touched objects or other touched willing creatures', 'instantaneous', 'none', 'no', 'You instantly transfer yourself from your current location to any other spot within range. You always arrive at exactly the spot desired—whether by simply visualizing the area or by stating direction. After using this spell, you can''t take any other actions until your next turn. You can bring along objects as long as their weight doesn''t exceed your maximum load. You may also bring one additional willing Medium or smaller creature (carrying gear or objects up to its maximum load) or its equivalent per three caster levels. A Large creature counts as two Medium creatures, a Huge creature counts as two Large creatures, and so forth. All creatures to be transported must be in contact with one another, and at least one of those creatures must be in contact with you.', NULL, NULL),
('e1000000-0000-0000-0000-000000000402', 'Remove Radioactivity', 'conjuration', '1 standard action', 'touch', NULL, 'one creature or object', 'instantaneous', 'Fort negates (harmless, object)', 'yes (harmless, object)', 'This spell instantly removes any and all radiation from the target creature or object and cures any radiation sickness or other radiation-based condition (including the irradiated condition) from which the target is suffering. It does not restore any ability score damage that may have resulted from the radiation.', NULL, NULL),

-- Level 5 (shared)
('e1000000-0000-0000-0000-000000000501', 'Commune with Nature', 'divination', '10 minutes', 'personal', NULL, 'you', 'instantaneous', 'none', 'no', 'You become one with nature, attuning your senses to the natural world around you. In natural surroundings, the spell tells you the following: the ground or terrain, the presence of bodies of water, the presence of minerals, the presence of plants and fungi, the presence of people, the kind and number of nondomesticated animals within range, the presence of toxic plants or poisonous animals, the general state of the natural setting. The spell functions only in natural settings—wilderness, mountains, or similar terrain. It does not work in urban or heavily built areas.', NULL, NULL),

-- Level 6 (shared)
('e1000000-0000-0000-0000-000000000601', 'Greater Dispel Magic', 'abjuration', '1 standard action', 'medium (100 ft. + 10 ft./level)', NULL, 'one spellcaster, creature, or object; or 20-ft.-radius burst', 'instantaneous', 'none', 'no', 'This spell functions like dispel magic, except that it can end more than one spell on a target and it can be used to target an area. The maximum number of spells dispelled is one spell per caster level (maximum 20 spells at caster level 20th). You choose to use greater dispel magic as a targeted dispel, area dispel, or counterspell. The DC to counter spells with greater dispel magic is 11 + the spell''s caster level.', NULL, NULL),
('e1000000-0000-0000-0000-000000000602', 'Planar Binding',     'conjuration', '10 minutes',        'close (25 ft. + 5 ft./2 levels)', NULL, 'one extraplanar creature', 'instantaneous', 'Will negates', 'no', 'Casting this spell attempts a dangerous act: to lure a creature from another plane to a specifically prepared trap, which must lie within the spell''s range. The called creature is held in the trap until it agrees to perform one service in return for its freedom, or until the spell expires. The duration of the trap is 3 days + 1 day per caster level. The trap must have a magic circle against chaos/evil/good/law around it to hold the creature. You can only bind creatures of CR 14 or lower. The creature can attempt to break free using a Strength check or escape artist, and may be coerced into service. Creatures that are unable to complete their bargain become hostile.', NULL, NULL);
