ALTER TABLE armor ADD COLUMN IF NOT EXISTS dr text, ADD COLUMN IF NOT EXISTS resistances text;

ALTER TABLE characters ADD COLUMN IF NOT EXISTS credits integer NOT NULL DEFAULT 0, ADD COLUMN IF NOT EXISTS xp_earned integer NOT NULL DEFAULT 0, ADD COLUMN IF NOT EXISTS languages text[] NOT NULL DEFAULT '{}';
